### ISSUE TITLE
Publish on crates.io?

### ISSUE THREAD

**Issue by Architector4** [DGriffin91/bevy_mod_mipmap_generator#3]
After lots of struggles of trying to converting textures around and trying to get things mipmapped, I casually found this crate, where just slotting it in magically makes all of my woes go away and fixes everything immediately. Thank you so much for this!

Despite the "converting slowly on CPU" nature of it (though it manages the job pretty fast in my case), this crate is a blessing, and in my opinion could use more discoverability and ease of access.

Is there any chance you might publish this on crates.io? That would be awesome and a great help for others not wanting to deal with manually converting stuff to KTX and the various behemoth tools that are written in C and need arcane compilation magic (maybe not but I've had lots of trouble trying to get anything to work) and their varying levels of support for glTF and stuff, whereas one can just slap this in and not deal with any of this, at least for now lol

**Comment by DGriffin91** [comment]
@Architector4 I'm glad this has been helpful! Bevy is in the middle of a large rework of the asset system that would dramatically change (and improve) how this should be done. (https://github.com/bevyengine/bevy/pull/8624) I think something like this crate (but better) will be built into bevy, hopefully in one of the next couple versions. With that being the case I probably won't be publishing this as it's mostly just a stop-gap.

I recommend using the commit hash to keep using the current revision. I'll also update this for bevy 0.11 when it comes out.

**Comment by Architector4** [comment]
Ah, that's fair. If something like that happens I'm personally unsure if Bevy will have this kind of a thing, but time will tell.

I'll keep using your crate here regardless. Thanks again!
